openapi: 3.0.0
info:
  title: Conatumex Server API
  description: API para gestionar clientes, compras y cobranzas.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Servidor local de desarrollo

tags:
  - name: Cobranza
    description: Endpoints relacionados con la gestión de cobranzas.

paths:
  /customer/cobrador/get-all-purchases:
    get:
      summary: Obtiene todas las compras activas del cobrador.
      description: Retorna una lista de compras activas asociadas al cobrador autenticado.
      tags:
        - Cobranza
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Lista de compras activas.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      client:
                        type: array
                        items:
                          $ref: '#/components/schemas/PurchaseModel'
                      dateUpdate:
                        type: string
                        format: date-time
        '401':
          description: No autorizado (token inválido o no proporcionado).
        '403':
          description: Acceso denegado (roles no válidos).

  /customer/cobrador/get-last-date-update:
    post:
      summary: Obtiene las compras actualizadas desde una fecha específica.
      description: Retorna las compras que han sido actualizadas después de la fecha proporcionada.
      tags:
        - Cobranza
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lastDateUpdate:
                  type: string
                  format: date-time
                  description: Fecha a partir de la cual se buscan actualizaciones.
      responses:
        '200':
          description: Lista de compras actualizadas.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      purchases:
                        type: array
                        items:
                          $ref: '#/components/schemas/PurchaseModel'
                      dateUpdate:
                        type: string
                        format: date-time
        '400':
          description: Solicitud inválida (fecha no proporcionada o en formato incorrecto).
        '401':
          description: No autorizado (token inválido o no proporcionado).
        '403':
          description: Acceso denegado (roles no válidos).

  /customer/cobrador/update-purchases:
    post:
      summary: Actualiza las compras del cobrador.
      description: Permite al cobrador actualizar las compras asociadas a su cuenta.
      tags:
        - Cobranza
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: array
                  items:
                    $ref: '#/components/schemas/PurchaseUpdateModel'
      responses:
        '200':
          description: Compras actualizadas correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      dateUpdate:
                        type: string
                        format: date-time
        '400':
          description: Solicitud inválida (datos no proporcionados o en formato incorrecto).
        '401':
          description: No autorizado (token inválido o no proporcionado).
        '403':
          description: Acceso denegado (roles no válidos).

  /customer/cobrador/actualize-data:
    post:
      summary: Actualiza los datos de las compras del cobrador.
      description: Permite al cobrador actualizar los datos de las compras y obtener las compras actualizadas desde una fecha específica.
      tags:
        - Cobranza
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: array
                  items:
                    $ref: '#/components/schemas/PurchaseUpdateModel'
                lastDateUpdate:
                  type: string
                  format: date-time
                  description: Fecha a partir de la cual se buscan actualizaciones.
      responses:
        '200':
          description: Datos actualizados correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      dateUpdate:
                        type: string
                        format: date-time
                      purchases:
                        type: array
                        items:
                          $ref: '#/components/schemas/PurchaseModel'
        '400':
          description: Solicitud inválida (datos no proporcionados o en formato incorrecto).
        '401':
          description: No autorizado (token inválido o no proporcionado).
        '403':
          description: Acceso denegado (roles no válidos).

  /customer/cobrador/ischange:
    post:
      summary: Verifica si las compras han cambiado de cobrador.
      description: Retorna las compras que han sido asignadas a otro cobrador.
      tags:
        - Cobranza
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: array
                  items:
                    type: string
                    description: ID de la compra.
      responses:
        '200':
          description: Compras que han cambiado de cobrador.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      dateUpdate:
                        type: string
                        format: date-time
        '400':
          description: Solicitud inválida (datos no proporcionados o en formato incorrecto).
        '401':
          description: No autorizado (token inválido o no proporcionado).
        '403':
          description: Acceso denegado (roles no válidos).

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    PurchaseModel:
      type: object
      properties:
        customerId:
          type: string
          format: objectId
          description: ID del cliente asociado a la compra.
        vendedorId:
          type: string
          format: objectId
          description: ID del vendedor asociado a la compra.
        cobradorId:
          type: string
          format: objectId
          description: ID del cobrador asociado a la compra.
        saleDate:
          type: string
          format: date-time
          description: Fecha de la venta.
        creditPrice:
          type: number
          description: Precio de la compra a crédito.
        cashPrice:
          type: number
          description: Precio de la compra al contado.
        cashPriceEndDate:
          type: string
          format: date-time
          description: Fecha límite para el precio al contado.
        collectionDate:
          type: string
          format: date-time
          description: Fecha de cobro programada.
        notes:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date-time
                description: Fecha de la nota.
              user:
                type: string
                format: objectId
                description: ID del usuario que agregó la nota.
              note:
                type: string
                description: Contenido de la nota.
        collectionFrequency:
          type: object
          properties:
            amount:
              type: string
              description: Monto de la frecuencia de cobro.
            frequency:
              type: string
              description: Frecuencia de cobro (diario, semanal, mensual).
        sentToCobrador:
          type: boolean
          description: Indica si la compra ha sido enviada al cobrador.
        products:
          type: array
          items:
            type: object
            properties:
              quantity:
                type: number
                description: Cantidad del producto.
              productId:
                type: string
                format: objectId
                description: ID del producto.
        totalPaid:
          type: number
          description: Total pagado hasta la fecha.
        payments:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date-time
                description: Fecha del pago.
              amount:
                type: number
                description: Monto del pago.
              receiptId:
                type: string
                description: ID del recibo de pago.
              userId:
                type: string
                format: objectId
                description: ID del usuario que registró el pago.
        updatedAt:
          type: string
          format: date-time
          description: Fecha de última actualización.
        statusId:
          type: string
          format: objectId
          description: ID del estado de la compra.
        isActive:
          type: boolean
          description: Indica si la compra está activa.

    PurchaseUpdateModel:
      type: object
      properties:
        id:
          type: string
          format: objectId
          description: ID de la compra a actualizar.
        collectionFrequency:
          type: object
          properties:
            amount:
              type: string
              description: Monto de la frecuencia de cobro.
            frequency:
              type: string
              description: Frecuencia de cobro (diario, semanal, mensual).
        notes:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date-time
                description: Fecha de la nota.
              user:
                type: string
                format: objectId
                description: ID del usuario que agregó la nota.
              note:
                type: string
                description: Contenido de la nota.
        payments:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date-time
                description: Fecha del pago.
              amount:
                type: number
                description: Monto del pago.
              receiptId:
                type: string
                description: ID del recibo de pago.
              userId:
                type: string
                format: objectId
                description: ID del usuario que registró el pago.